### ISSUE TITLE
no way to opt out (EULA)

### ISSUE THREAD

**Issue by smisch** [iChun/iChunUtil#155]
Your EULA says "You also permit, but may opt out of in the configuration file, the Mod to collect and use [...]", but the configuration files do not seem to contain lines to actually opt out. 

Checked config files:
config/ichunutil.cfg
config/ichunutil_keybinds.cfg

This might just be a documentation issue.

**Comment by iChun** [comment]
Ah nah that's just some outdated stuff in the EULA that I'm yet to
implement. The mod used to collect some data for a worldwide "infection"
social test I was doing but it was scrapped in favour for a new version
which I haven't written yet which is why it's still in the EULA.

TL;DR, yeah just outdated EULA.


On 7 Oct 2017 7:24 pm, "Sebastian" <notifications@github.com> wrote:

Your EULA says "You also permit, but may opt out of in the configuration
file, the Mod to collect and use [...]", but the configuration files do not
seem to contain lines to actually opt out.

Checked config files:
config/ichunutil.cfg
config/ichunutil_keybinds.cfg

This might just be a documentation issue.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/iChunUtil/issues/155>, or mute the thread
