### ISSUE TITLE
Keybinds need to be registered to the Controls menu.

### ISSUE THREAD

**Issue by Dragnier** [iChun/iChunUtil#184]
The entire reason Minecraft has a controls menu is to allow a centralized place to adjust said controls for anything in game that can have a configurable keybind. Hiding your keybinds in a separate menu that also doesn't show it's keybind in the controls menu makes for a frustrating end-user experience.

Further, modpack makers tend to use things like the Default Options mod to ship pre-defined custom keybinds with their modpack. This does not work with your current keybinds.

Potential fixes could be registering the iChun util options keybind into the controls menu only, registering all keybinds to the controls menu, or making an in-game manual that informs the player about the mods configuration options.

Of those fixes, I think I would favor the first one. As long as the options menu key was registered, end-users could find that and further configure your mods as intended.

**Comment by iChun** [comment]
The reason iChunUtil's keybinds are in a different menu is because I added support for key modifiers such as Ctrl, Shift, Alt, before it became a thing in Forge. I used to have a notice in the controls menu but it caused some compatibility issues with other mods so I removed it.

I will be shifting the Keybinds to use Forge's in the future. It's slated for 1.13.
