### ISSUE TITLE
[1.16.5] Crash while I was flying around

### ISSUE THREAD

**Issue by stanlexgreenson** [iChun/iChunUtil#230]
Hello, my game crashed twice while I was flying around in creative mode in a newly created survival single player world. I asked for help in the curseforge discord to identify the reason of the crash since I still dont understand how to identify them myself, someone said it may be an issue with this mod.

In any case this detail help: while it was daytime there where no crashes, it started crashing when mobs where spawning in night time.

Forge version 36.2.34
iChunUtil-1.16.5-10.6.0

[latest.log](https://github.com/iChun/iChunUtil/files/8762518/latest.log)
[crash-2022-05-24_07.34.15-server.txt](https://github.com/iChun/iChunUtil/files/8762561/crash-2022-05-24_07.34.15-server.txt)

**Comment by iChun** [comment]
I don't think the crash isn't caused by iChunUtil. None of my mods touch or mess with mob spawning. 

However, iChunUtil is throwing out an exception with it's configs due to the server shutting down due to the crash, which is probably what sent you this way, but it's not the main reason for the crash.

**Comment by iChun** [comment]
I know this prolly isn't helpful but I don't know which mods are causing your crash, since the crash's stack trace doesn't really point to any mod in particular

**Comment by iChun** [comment]
I've fixed the config issue, it'll be in the 10.6.1 update.
